name        : liboauth
version     : 1.0.3
release     : 3
source      :
    - http://downloads.sourceforge.net/liboauth/liboauth-1.0.3.tar.gz : 0df60157b052f0e774ade8a8bac59d6e8d4b464058cc55f9208d72e41156811f
homepage    : http://liboauth.sourceforge.net
license     : MIT
component   : network.base
libsplit    : no
summary     : Library implementing OAuth Core RFC 5849 standard
description : |
    liboauth is a collection of POSIX-C functions implementing the OAuth Core RFC 5849 standard. Liboauth provides functions to escape and encode parameters according to OAuth specification and offers high-level functionality to sign requests or verify OAuth signatures as well as perform HTTP requests.
builddeps   :
    - pkgconfig(libcurl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
